__LABEL__:
swieq #0x0
swine #0x0
swics #0x0
swicc #0x0
swimi #0x0
swipl #0x0
swivs #0x0
swivc #0x0
swihi #0x0
swils #0x0
swige #0x0
swilt #0x0
swigt #0x0
swile #0x0
swial #0x0
clzeq r0, r0
clzne r0, r0
clzcs r0, r0
clzcc r0, r0
clzmi r0, r0
clzpl r0, r0
clzvs r0, r0
clzvc r0, r0
clzhi r0, r0
clzls r0, r0
clzge r0, r0
clzlt r0, r0
clzgt r0, r0
clzle r0, r0
clzal r0, r0
tsteq r0, r0
tstne r0, r0
tstcs r0, r0
tstcc r0, r0
tstmi r0, r0
tstpl r0, r0
tstvs r0, r0
tstvc r0, r0
tsthi r0, r0
tstls r0, r0
tstge r0, r0
tstlt r0, r0
tstgt r0, r0
tstle r0, r0
tstal r0, r0
teqeq r0, r0
teqne r0, r0
teqcs r0, r0
teqcc r0, r0
teqmi r0, r0
teqpl r0, r0
teqvs r0, r0
teqvc r0, r0
teqhi r0, r0
teqls r0, r0
teqge r0, r0
teqlt r0, r0
teqgt r0, r0
teqle r0, r0
teqal r0, r0
cmpeq r0, r0
cmpne r0, r0
cmpcs r0, r0
cmpcc r0, r0
cmpmi r0, r0
cmppl r0, r0
cmpvs r0, r0
cmpvc r0, r0
cmphi r0, r0
cmpls r0, r0
cmpge r0, r0
cmplt r0, r0
cmpgt r0, r0
cmple r0, r0
cmpal r0, r0
cmneq r0, r0
cmnne r0, r0
cmncs r0, r0
cmncc r0, r0
cmnmi r0, r0
cmnpl r0, r0
cmnvs r0, r0
cmnvc r0, r0
cmnhi r0, r0
cmnls r0, r0
cmnge r0, r0
cmnlt r0, r0
cmngt r0, r0
cmnle r0, r0
cmnal r0, r0
moveq r0, r0
movne r0, r0
movcs r0, r0
movcc r0, r0
movmi r0, r0
movpl r0, r0
movvs r0, r0
movvc r0, r0
movhi r0, r0
movls r0, r0
movge r0, r0
movlt r0, r0
movgt r0, r0
movle r0, r0
moval r0, r0
mvneq r0, r0
mvnne r0, r0
mvncs r0, r0
mvncc r0, r0
mvnmi r0, r0
mvnpl r0, r0
mvnvs r0, r0
mvnvc r0, r0
mvnhi r0, r0
mvnls r0, r0
mvnge r0, r0
mvnlt r0, r0
mvngt r0, r0
mvnle r0, r0
mvnal r0, r0
andeq r0, r1, r2
andne r0, r1, r2
andcs r0, r1, r2
andcc r0, r1, r2
andmi r0, r1, r2
andpl r0, r1, r2
andvs r0, r1, r2
andvc r0, r1, r2
andhi r0, r1, r2
andls r0, r1, r2
andge r0, r1, r2
andlt r0, r1, r2
andgt r0, r1, r2
andle r0, r1, r2
andal r0, r1, r2
eoreq r0, r1, r2
eorne r0, r1, r2
eorcs r0, r1, r2
eorcc r0, r1, r2
eormi r0, r1, r2
eorpl r0, r1, r2
eorvs r0, r1, r2
eorvc r0, r1, r2
eorhi r0, r1, r2
eorls r0, r1, r2
eorge r0, r1, r2
eorlt r0, r1, r2
eorgt r0, r1, r2
eorle r0, r1, r2
eoral r0, r1, r2
subeq r0, r1, r2
subne r0, r1, r2
subcs r0, r1, r2
subcc r0, r1, r2
submi r0, r1, r2
subpl r0, r1, r2
subvs r0, r1, r2
subvc r0, r1, r2
subhi r0, r1, r2
subls r0, r1, r2
subge r0, r1, r2
sublt r0, r1, r2
subgt r0, r1, r2
suble r0, r1, r2
subal r0, r1, r2
rsbeq r0, r1, r2
rsbne r0, r1, r2
rsbcs r0, r1, r2
rsbcc r0, r1, r2
rsbmi r0, r1, r2
rsbpl r0, r1, r2
rsbvs r0, r1, r2
rsbvc r0, r1, r2
rsbhi r0, r1, r2
rsbls r0, r1, r2
rsbge r0, r1, r2
rsblt r0, r1, r2
rsbgt r0, r1, r2
rsble r0, r1, r2
rsbal r0, r1, r2
addeq r0, r1, r2
addne r0, r1, r2
addcs r0, r1, r2
addcc r0, r1, r2
addmi r0, r1, r2
addpl r0, r1, r2
addvs r0, r1, r2
addvc r0, r1, r2
addhi r0, r1, r2
addls r0, r1, r2
addge r0, r1, r2
addlt r0, r1, r2
addgt r0, r1, r2
addle r0, r1, r2
addal r0, r1, r2
adceq r0, r1, r2
adcne r0, r1, r2
adccs r0, r1, r2
adccc r0, r1, r2
adcmi r0, r1, r2
adcpl r0, r1, r2
adcvs r0, r1, r2
adcvc r0, r1, r2
adchi r0, r1, r2
adcls r0, r1, r2
adcge r0, r1, r2
adclt r0, r1, r2
adcgt r0, r1, r2
adcle r0, r1, r2
adcal r0, r1, r2
sbceq r0, r1, r2
sbcne r0, r1, r2
sbccs r0, r1, r2
sbccc r0, r1, r2
sbcmi r0, r1, r2
sbcpl r0, r1, r2
sbcvs r0, r1, r2
sbcvc r0, r1, r2
sbchi r0, r1, r2
sbcls r0, r1, r2
sbcge r0, r1, r2
sbclt r0, r1, r2
sbcgt r0, r1, r2
sbcle r0, r1, r2
sbcal r0, r1, r2
rsceq r0, r1, r2
rscne r0, r1, r2
rsccs r0, r1, r2
rsccc r0, r1, r2
rscmi r0, r1, r2
rscpl r0, r1, r2
rscvs r0, r1, r2
rscvc r0, r1, r2
rschi r0, r1, r2
rscls r0, r1, r2
rscge r0, r1, r2
rsclt r0, r1, r2
rscgt r0, r1, r2
rscle r0, r1, r2
rscal r0, r1, r2
orreq r0, r1, r2
orrne r0, r1, r2
orrcs r0, r1, r2
orrcc r0, r1, r2
orrmi r0, r1, r2
orrpl r0, r1, r2
orrvs r0, r1, r2
orrvc r0, r1, r2
orrhi r0, r1, r2
orrls r0, r1, r2
orrge r0, r1, r2
orrlt r0, r1, r2
orrgt r0, r1, r2
orrle r0, r1, r2
orral r0, r1, r2
biceq r0, r1, r2
bicne r0, r1, r2
biccs r0, r1, r2
biccc r0, r1, r2
bicmi r0, r1, r2
bicpl r0, r1, r2
bicvs r0, r1, r2
bicvc r0, r1, r2
bichi r0, r1, r2
bicls r0, r1, r2
bicge r0, r1, r2
biclt r0, r1, r2
bicgt r0, r1, r2
bicle r0, r1, r2
bical r0, r1, r2
muleq r0, r1, r2
mulne r0, r1, r2
mulcs r0, r1, r2
mulcc r0, r1, r2
mulmi r0, r1, r2
mulpl r0, r1, r2
mulvs r0, r1, r2
mulvc r0, r1, r2
mulhi r0, r1, r2
mulls r0, r1, r2
mulge r0, r1, r2
mullt r0, r1, r2
mulgt r0, r1, r2
mulle r0, r1, r2
mulal r0, r1, r2
mlaeq r0, r1, r2, r3
mlane r0, r1, r2, r3
mlacs r0, r1, r2, r3
mlacc r0, r1, r2, r3
mlami r0, r1, r2, r3
mlapl r0, r1, r2, r3
mlavs r0, r1, r2, r3
mlavc r0, r1, r2, r3
mlahi r0, r1, r2, r3
mlals r0, r1, r2, r3
mlage r0, r1, r2, r3
mlalt r0, r1, r2, r3
mlagt r0, r1, r2, r3
mlale r0, r1, r2, r3
mlaal r0, r1, r2, r3
umulleq r0, r1, r2, r3
umullne r0, r1, r2, r3
umullcs r0, r1, r2, r3
umullcc r0, r1, r2, r3
umullmi r0, r1, r2, r3
umullpl r0, r1, r2, r3
umullvs r0, r1, r2, r3
umullvc r0, r1, r2, r3
umullhi r0, r1, r2, r3
umullls r0, r1, r2, r3
umullge r0, r1, r2, r3
umulllt r0, r1, r2, r3
umullgt r0, r1, r2, r3
umullle r0, r1, r2, r3
umullal r0, r1, r2, r3
umlaleq r0, r1, r2, r3
umlalne r0, r1, r2, r3
umlalcs r0, r1, r2, r3
umlalcc r0, r1, r2, r3
umlalmi r0, r1, r2, r3
umlalpl r0, r1, r2, r3
umlalvs r0, r1, r2, r3
umlalvc r0, r1, r2, r3
umlalhi r0, r1, r2, r3
umlalls r0, r1, r2, r3
umlalge r0, r1, r2, r3
umlallt r0, r1, r2, r3
umlalgt r0, r1, r2, r3
umlalle r0, r1, r2, r3
umlalal r0, r1, r2, r3
smulleq r0, r1, r2, r3
smullne r0, r1, r2, r3
smullcs r0, r1, r2, r3
smullcc r0, r1, r2, r3
smullmi r0, r1, r2, r3
smullpl r0, r1, r2, r3
smullvs r0, r1, r2, r3
smullvc r0, r1, r2, r3
smullhi r0, r1, r2, r3
smullls r0, r1, r2, r3
smullge r0, r1, r2, r3
smulllt r0, r1, r2, r3
smullgt r0, r1, r2, r3
smullle r0, r1, r2, r3
smullal r0, r1, r2, r3
smlaleq r0, r1, r2, r3
smlalne r0, r1, r2, r3
smlalcs r0, r1, r2, r3
smlalcc r0, r1, r2, r3
smlalmi r0, r1, r2, r3
smlalpl r0, r1, r2, r3
smlalvs r0, r1, r2, r3
smlalvc r0, r1, r2, r3
smlalhi r0, r1, r2, r3
smlalls r0, r1, r2, r3
smlalge r0, r1, r2, r3
smlallt r0, r1, r2, r3
smlalgt r0, r1, r2, r3
smlalle r0, r1, r2, r3
smlalal r0, r1, r2, r3
ldreqb r0, [r1]
ldrneb r0, [r1]
ldrcsb r0, [r1]
ldrccb r0, [r1]
ldrmib r0, [r1]
ldrplb r0, [r1]
ldrvsb r0, [r1]
ldrvcb r0, [r1]
ldrhib r0, [r1]
ldrlsb r0, [r1]
ldrgeb r0, [r1]
ldrltb r0, [r1]
ldrgtb r0, [r1]
ldrleb r0, [r1]
ldralb r0, [r1]
ldreqh r0, [r1]
ldrneh r0, [r1]
ldrcsh r0, [r1]
ldrcch r0, [r1]
ldrmih r0, [r1]
ldrplh r0, [r1]
ldrvsh r0, [r1]
ldrvch r0, [r1]
ldrhih r0, [r1]
ldrlsh r0, [r1]
ldrgeh r0, [r1]
ldrlth r0, [r1]
ldrgth r0, [r1]
ldrleh r0, [r1]
ldralh r0, [r1]
ldreqsh r0, [r1]
ldrnesh r0, [r1]
ldrcssh r0, [r1]
ldrccsh r0, [r1]
ldrmish r0, [r1]
ldrplsh r0, [r1]
ldrvssh r0, [r1]
ldrvcsh r0, [r1]
ldrhish r0, [r1]
ldrlssh r0, [r1]
ldrgesh r0, [r1]
ldrltsh r0, [r1]
ldrgtsh r0, [r1]
ldrlesh r0, [r1]
ldralsh r0, [r1]
ldreqsb r0, [r1]
ldrnesb r0, [r1]
ldrcssb r0, [r1]
ldrccsb r0, [r1]
ldrmisb r0, [r1]
ldrplsb r0, [r1]
ldrvssb r0, [r1]
ldrvcsb r0, [r1]
ldrhisb r0, [r1]
ldrlssb r0, [r1]
ldrgesb r0, [r1]
ldrltsb r0, [r1]
ldrgtsb r0, [r1]
ldrlesb r0, [r1]
ldralsb r0, [r1]
streqb r0, [r1]
strneb r0, [r1]
strcsb r0, [r1]
strccb r0, [r1]
strmib r0, [r1]
strplb r0, [r1]
strvsb r0, [r1]
strvcb r0, [r1]
strhib r0, [r1]
strlsb r0, [r1]
strgeb r0, [r1]
strltb r0, [r1]
strgtb r0, [r1]
strleb r0, [r1]
stralb r0, [r1]
streqh r0, [r1]
strneh r0, [r1]
strcsh r0, [r1]
strcch r0, [r1]
strmih r0, [r1]
strplh r0, [r1]
strvsh r0, [r1]
strvch r0, [r1]
strhih r0, [r1]
strlsh r0, [r1]
strgeh r0, [r1]
strlth r0, [r1]
strgth r0, [r1]
strleh r0, [r1]
stralh r0, [r1]
ldmeqib r0, {r1, r2, r3}
ldmneib r0, {r1, r2, r3}
ldmcsib r0, {r1, r2, r3}
ldmccib r0, {r1, r2, r3}
ldmmiib r0, {r1, r2, r3}
ldmplib r0, {r1, r2, r3}
ldmvsib r0, {r1, r2, r3}
ldmvcib r0, {r1, r2, r3}
ldmhiib r0, {r1, r2, r3}
ldmlsib r0, {r1, r2, r3}
ldmgeib r0, {r1, r2, r3}
ldmltib r0, {r1, r2, r3}
ldmgtib r0, {r1, r2, r3}
ldmleib r0, {r1, r2, r3}
ldmalib r0, {r1, r2, r3}
ldmeqia r0, {r1, r2, r3}
ldmneia r0, {r1, r2, r3}
ldmcsia r0, {r1, r2, r3}
ldmccia r0, {r1, r2, r3}
ldmmiia r0, {r1, r2, r3}
ldmplia r0, {r1, r2, r3}
ldmvsia r0, {r1, r2, r3}
ldmvcia r0, {r1, r2, r3}
ldmhiia r0, {r1, r2, r3}
ldmlsia r0, {r1, r2, r3}
ldmgeia r0, {r1, r2, r3}
ldmltia r0, {r1, r2, r3}
ldmgtia r0, {r1, r2, r3}
ldmleia r0, {r1, r2, r3}
ldmalia r0, {r1, r2, r3}
ldmeqdb r0, {r1, r2, r3}
ldmnedb r0, {r1, r2, r3}
ldmcsdb r0, {r1, r2, r3}
ldmccdb r0, {r1, r2, r3}
ldmmidb r0, {r1, r2, r3}
ldmpldb r0, {r1, r2, r3}
ldmvsdb r0, {r1, r2, r3}
ldmvcdb r0, {r1, r2, r3}
ldmhidb r0, {r1, r2, r3}
ldmlsdb r0, {r1, r2, r3}
ldmgedb r0, {r1, r2, r3}
ldmltdb r0, {r1, r2, r3}
ldmgtdb r0, {r1, r2, r3}
ldmledb r0, {r1, r2, r3}
ldmaldb r0, {r1, r2, r3}
ldmeqda r0, {r1, r2, r3}
ldmneda r0, {r1, r2, r3}
ldmcsda r0, {r1, r2, r3}
ldmccda r0, {r1, r2, r3}
ldmmida r0, {r1, r2, r3}
ldmplda r0, {r1, r2, r3}
ldmvsda r0, {r1, r2, r3}
ldmvcda r0, {r1, r2, r3}
ldmhida r0, {r1, r2, r3}
ldmlsda r0, {r1, r2, r3}
ldmgeda r0, {r1, r2, r3}
ldmltda r0, {r1, r2, r3}
ldmgtda r0, {r1, r2, r3}
ldmleda r0, {r1, r2, r3}
ldmalda r0, {r1, r2, r3}
ldmeqfa r0, {r1, r2, r3}
ldmnefa r0, {r1, r2, r3}
ldmcsfa r0, {r1, r2, r3}
ldmccfa r0, {r1, r2, r3}
ldmmifa r0, {r1, r2, r3}
ldmplfa r0, {r1, r2, r3}
ldmvsfa r0, {r1, r2, r3}
ldmvcfa r0, {r1, r2, r3}
ldmhifa r0, {r1, r2, r3}
ldmlsfa r0, {r1, r2, r3}
ldmgefa r0, {r1, r2, r3}
ldmltfa r0, {r1, r2, r3}
ldmgtfa r0, {r1, r2, r3}
ldmlefa r0, {r1, r2, r3}
ldmalfa r0, {r1, r2, r3}
ldmeqea r0, {r1, r2, r3}
ldmneea r0, {r1, r2, r3}
ldmcsea r0, {r1, r2, r3}
ldmccea r0, {r1, r2, r3}
ldmmiea r0, {r1, r2, r3}
ldmplea r0, {r1, r2, r3}
ldmvsea r0, {r1, r2, r3}
ldmvcea r0, {r1, r2, r3}
ldmhiea r0, {r1, r2, r3}
ldmlsea r0, {r1, r2, r3}
ldmgeea r0, {r1, r2, r3}
ldmltea r0, {r1, r2, r3}
ldmgtea r0, {r1, r2, r3}
ldmleea r0, {r1, r2, r3}
ldmalea r0, {r1, r2, r3}
ldmeqfd r0, {r1, r2, r3}
ldmnefd r0, {r1, r2, r3}
ldmcsfd r0, {r1, r2, r3}
ldmccfd r0, {r1, r2, r3}
ldmmifd r0, {r1, r2, r3}
ldmplfd r0, {r1, r2, r3}
ldmvsfd r0, {r1, r2, r3}
ldmvcfd r0, {r1, r2, r3}
ldmhifd r0, {r1, r2, r3}
ldmlsfd r0, {r1, r2, r3}
ldmgefd r0, {r1, r2, r3}
ldmltfd r0, {r1, r2, r3}
ldmgtfd r0, {r1, r2, r3}
ldmlefd r0, {r1, r2, r3}
ldmalfd r0, {r1, r2, r3}
ldmeqed r0, {r1, r2, r3}
ldmneed r0, {r1, r2, r3}
ldmcsed r0, {r1, r2, r3}
ldmcced r0, {r1, r2, r3}
ldmmied r0, {r1, r2, r3}
ldmpled r0, {r1, r2, r3}
ldmvsed r0, {r1, r2, r3}
ldmvced r0, {r1, r2, r3}
ldmhied r0, {r1, r2, r3}
ldmlsed r0, {r1, r2, r3}
ldmgeed r0, {r1, r2, r3}
ldmlted r0, {r1, r2, r3}
ldmgted r0, {r1, r2, r3}
ldmleed r0, {r1, r2, r3}
ldmaled r0, {r1, r2, r3}
stmeqib r0, {r1, r2, r3}
stmneib r0, {r1, r2, r3}
stmcsib r0, {r1, r2, r3}
stmccib r0, {r1, r2, r3}
stmmiib r0, {r1, r2, r3}
stmplib r0, {r1, r2, r3}
stmvsib r0, {r1, r2, r3}
stmvcib r0, {r1, r2, r3}
stmhiib r0, {r1, r2, r3}
stmlsib r0, {r1, r2, r3}
stmgeib r0, {r1, r2, r3}
stmltib r0, {r1, r2, r3}
stmgtib r0, {r1, r2, r3}
stmleib r0, {r1, r2, r3}
stmalib r0, {r1, r2, r3}
stmeqia r0, {r1, r2, r3}
stmneia r0, {r1, r2, r3}
stmcsia r0, {r1, r2, r3}
stmccia r0, {r1, r2, r3}
stmmiia r0, {r1, r2, r3}
stmplia r0, {r1, r2, r3}
stmvsia r0, {r1, r2, r3}
stmvcia r0, {r1, r2, r3}
stmhiia r0, {r1, r2, r3}
stmlsia r0, {r1, r2, r3}
stmgeia r0, {r1, r2, r3}
stmltia r0, {r1, r2, r3}
stmgtia r0, {r1, r2, r3}
stmleia r0, {r1, r2, r3}
stmalia r0, {r1, r2, r3}
stmeqdb r0, {r1, r2, r3}
stmnedb r0, {r1, r2, r3}
stmcsdb r0, {r1, r2, r3}
stmccdb r0, {r1, r2, r3}
stmmidb r0, {r1, r2, r3}
stmpldb r0, {r1, r2, r3}
stmvsdb r0, {r1, r2, r3}
stmvcdb r0, {r1, r2, r3}
stmhidb r0, {r1, r2, r3}
stmlsdb r0, {r1, r2, r3}
stmgedb r0, {r1, r2, r3}
stmltdb r0, {r1, r2, r3}
stmgtdb r0, {r1, r2, r3}
stmledb r0, {r1, r2, r3}
stmaldb r0, {r1, r2, r3}
stmeqda r0, {r1, r2, r3}
stmneda r0, {r1, r2, r3}
stmcsda r0, {r1, r2, r3}
stmccda r0, {r1, r2, r3}
stmmida r0, {r1, r2, r3}
stmplda r0, {r1, r2, r3}
stmvsda r0, {r1, r2, r3}
stmvcda r0, {r1, r2, r3}
stmhida r0, {r1, r2, r3}
stmlsda r0, {r1, r2, r3}
stmgeda r0, {r1, r2, r3}
stmltda r0, {r1, r2, r3}
stmgtda r0, {r1, r2, r3}
stmleda r0, {r1, r2, r3}
stmalda r0, {r1, r2, r3}
stmeqfa r0, {r1, r2, r3}
stmnefa r0, {r1, r2, r3}
stmcsfa r0, {r1, r2, r3}
stmccfa r0, {r1, r2, r3}
stmmifa r0, {r1, r2, r3}
stmplfa r0, {r1, r2, r3}
stmvsfa r0, {r1, r2, r3}
stmvcfa r0, {r1, r2, r3}
stmhifa r0, {r1, r2, r3}
stmlsfa r0, {r1, r2, r3}
stmgefa r0, {r1, r2, r3}
stmltfa r0, {r1, r2, r3}
stmgtfa r0, {r1, r2, r3}
stmlefa r0, {r1, r2, r3}
stmalfa r0, {r1, r2, r3}
stmeqea r0, {r1, r2, r3}
stmneea r0, {r1, r2, r3}
stmcsea r0, {r1, r2, r3}
stmccea r0, {r1, r2, r3}
stmmiea r0, {r1, r2, r3}
stmplea r0, {r1, r2, r3}
stmvsea r0, {r1, r2, r3}
stmvcea r0, {r1, r2, r3}
stmhiea r0, {r1, r2, r3}
stmlsea r0, {r1, r2, r3}
stmgeea r0, {r1, r2, r3}
stmltea r0, {r1, r2, r3}
stmgtea r0, {r1, r2, r3}
stmleea r0, {r1, r2, r3}
stmalea r0, {r1, r2, r3}
stmeqfd r0, {r1, r2, r3}
stmnefd r0, {r1, r2, r3}
stmcsfd r0, {r1, r2, r3}
stmccfd r0, {r1, r2, r3}
stmmifd r0, {r1, r2, r3}
stmplfd r0, {r1, r2, r3}
stmvsfd r0, {r1, r2, r3}
stmvcfd r0, {r1, r2, r3}
stmhifd r0, {r1, r2, r3}
stmlsfd r0, {r1, r2, r3}
stmgefd r0, {r1, r2, r3}
stmltfd r0, {r1, r2, r3}
stmgtfd r0, {r1, r2, r3}
stmlefd r0, {r1, r2, r3}
stmalfd r0, {r1, r2, r3}
stmeqed r0, {r1, r2, r3}
stmneed r0, {r1, r2, r3}
stmcsed r0, {r1, r2, r3}
stmcced r0, {r1, r2, r3}
stmmied r0, {r1, r2, r3}
stmpled r0, {r1, r2, r3}
stmvsed r0, {r1, r2, r3}
stmvced r0, {r1, r2, r3}
stmhied r0, {r1, r2, r3}
stmlsed r0, {r1, r2, r3}
stmgeed r0, {r1, r2, r3}
stmlted r0, {r1, r2, r3}
stmgted r0, {r1, r2, r3}
stmleed r0, {r1, r2, r3}
stmaled r0, {r1, r2, r3}
beq __LABEL__
bleq __LABEL__
bxeq lr
bne __LABEL__
blne __LABEL__
bxne lr
bcs __LABEL__
blcs __LABEL__
bxcs lr
bcc __LABEL__
blcc __LABEL__
bxcc lr
bmi __LABEL__
blmi __LABEL__
bxmi lr
bpl __LABEL__
blpl __LABEL__
bxpl lr
bvs __LABEL__
blvs __LABEL__
bxvs lr
bvc __LABEL__
blvc __LABEL__
bxvc lr
bhi __LABEL__
blhi __LABEL__
bxhi lr
bls __LABEL__
blls __LABEL__
bxls lr
bge __LABEL__
blge __LABEL__
bxge lr
blt __LABEL__
bllt __LABEL__
bxlt lr
bgt __LABEL__
blgt __LABEL__
bxgt lr
ble __LABEL__
blle __LABEL__
bxle lr
bal __LABEL__
blal __LABEL__
bxal lr
swpeq r0, r1, [r2]
swpeq r0, r1, [r2]
swpne r0, r1, [r2]
swpne r0, r1, [r2]
swpcs r0, r1, [r2]
swpcs r0, r1, [r2]
swpcc r0, r1, [r2]
swpcc r0, r1, [r2]
swpmi r0, r1, [r2]
swpmi r0, r1, [r2]
swppl r0, r1, [r2]
swppl r0, r1, [r2]
swpvs r0, r1, [r2]
swpvs r0, r1, [r2]
swpvc r0, r1, [r2]
swpvc r0, r1, [r2]
swphi r0, r1, [r2]
swphi r0, r1, [r2]
swpls r0, r1, [r2]
swpls r0, r1, [r2]
swpge r0, r1, [r2]
swpge r0, r1, [r2]
swplt r0, r1, [r2]
swplt r0, r1, [r2]
swpgt r0, r1, [r2]
swpgt r0, r1, [r2]
swple r0, r1, [r2]
swple r0, r1, [r2]
swpal r0, r1, [r2]
swpal r0, r1, [r2]
mrseq r0, CPSR
msreq CPSR, r0
mrsne r0, CPSR
msrne CPSR, r0
mrscs r0, CPSR
msrcs CPSR, r0
mrscc r0, CPSR
msrcc CPSR, r0
mrsmi r0, CPSR
msrmi CPSR, r0
mrspl r0, CPSR
msrpl CPSR, r0
mrsvs r0, CPSR
msrvs CPSR, r0
mrsvc r0, CPSR
msrvc CPSR, r0
mrshi r0, CPSR
msrhi CPSR, r0
mrsls r0, CPSR
msrls CPSR, r0
mrsge r0, CPSR
msrge CPSR, r0
mrslt r0, CPSR
msrlt CPSR, r0
mrsgt r0, CPSR
msrgt CPSR, r0
mrsle r0, CPSR
msrle CPSR, r0
mrsal r0, CPSR
msral CPSR, r0
